"""
Copyright 2015, University of Freiburg.

Elmar Haussmann <haussmann@cs.uni-freiburg.de>
"""
from query_translator import ranker
from collections import OrderedDict

free917_entities = "evaluation-data/free917_entities.txt"

scorer_list = None
scorers_dict = None
DATASETS = None


def init():
    global scorer_list
    global scorers_dict
    global DATASETS
    # The scorers that can be selected.
    scorer_list = [ranker.AccuModel('F917_Ranker',
                                     "free917train",
                                     top_ngram_percentile=2,
                                     rel_regularization_C=0.002),
                   ranker.AccuModel('F917_Ranker_entity_oracle',
                                     "free917train",
                                     entity_oracle_file=free917_entities,
                                     top_ngram_percentile=2,
                                     rel_regularization_C=1.0),
                   ranker.AccuModel('WQ_Ranker',
                                     "webquestionstrain",
                                     top_ngram_percentile=5,
                                     rel_regularization_C=1.0),
                   ranker.AccuModel('WQ_Ranker_ExtraTemplates',
                                    "webquestions_test_filter",
                                    top_ngram_percentile=5,
                                    ranking_algorithm='random_forest',
                                    ranking_n_estimators=100,
                                    rel_regularization_C=1.0,
                                    extract_text_features_pruning=False,
                                    extract_text_features_ranking=False,
                                    extract_cqa_features_ranking=False,
                                    extract_cqa_features_pruning=False,
                                    use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_EmbeddingRelModel',
                                    "webquestions_split_train",
                                    use_embeddings_relation_model=True,
                                    ranking_algorithm='random_forest',
                                    ranking_n_estimators=100,
                                    rel_regularization_C=1.0,
                                    extract_text_features_pruning=False,
                                    extract_text_features_ranking=False,
                                    extract_cqa_features_ranking=False,
                                    extract_cqa_features_pruning=False,
                                    use_pruning=True),

                   ranker.AccuModel('WQ_Ranker_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     rel_regularization_C=1.0),

                   ranker.AccuModel('WQ_Ranker_Types_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     rel_regularization_C=1.0),

                   ranker.AccuModel('WQ_Ranker_NoPruning_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     rel_regularization_C=1.0,
                                     use_pruning=False),
                   ranker.AccuModel('WQ_Ranker_ExternalEntities',
                                     "webquestionstrain_externalentities",
                                     top_ngram_percentile=5,
                                     rel_regularization_C=1.0),
                   ranker.AccuModel('WQ_Ranker_WithTextRank',
                                     "webquestionstrain",
                                     top_ngram_percentile=5,
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=True,
                                     use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_WithTextPruneRank',
                                     "webquestionstrain",
                                     top_ngram_percentile=5,
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=True,
                                     extract_text_features_ranking=True,
                                     use_pruning=True),

                   # Baseline models with more iterations
                   ranker.AccuModel('WQ_Ranker_RF100_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=False,
                                     use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_RF500_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     ranking_n_estimators=500,
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=False,
                                     use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_RF1000_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     ranking_n_estimators=1000,
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=False,
                                     use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_RF100_DateRange_Dev',
                                     "webquestions_split_train_daterange",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     ranking_n_estimators=100,
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=False,
                                     use_pruning=True),

                   ranker.AccuModel('WQ_Ranker_RF100_TypeFilter_Dev',
                                     "webquestions_split_train_typefilter",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     ranking_n_estimators=100,
                                     rel_regularization_C=1.0,
                                     use_type_model=False,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=False,
                                     use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_RF100_TypeFilterModel_Dev',
                                     "webquestions_split_train_typefilter",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     ranking_n_estimators=100,
                                     rel_regularization_C=1.0,
                                     use_type_model=True,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=False,
                                     use_pruning=True),

                   # Baselines with external entities
                   ranker.AccuModel('WQ_Ranker_ExtEnt_All_RF100_Dev',
                                     "webquestions_split_train_externalentities_all",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=False,
                                     use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_ExtEnt_All_RF100',
                                     "webquestions_train_externalentities_all",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=False,
                                     use_pruning=True),

                   # Text models with more iterations
                   ranker.AccuModel('WQ_Ranker_WithTextRank_RF100_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     ranking_n_estimators=100,
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=True,
                                     use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_WithTextRank_RF1000_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     ranking_n_estimators=1000,
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=True,
                                     use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_WithTextRankPrune_RF100_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     ranking_n_estimators=100,
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=True,
                                     extract_text_features_ranking=True,
                                     use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_WithTextRankPrune_RF1000_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     ranking_n_estimators=1000,
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=True,
                                     extract_text_features_ranking=True,
                                     use_pruning=True),
                  ranker.AccuModel('WQ_Ranker_WithTextRankNoPrune_RF1000_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     ranking_algorithm='random_forest',
                                     ranking_n_estimators=1000,
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=True,
                                     extract_text_features_ranking=True,
                                     use_pruning=False),

                  # Using CQA and text features
                  ranker.AccuModel('WQ_Ranker_WithTextCqaRank_RF100_Dev',
                                   "webquestions_split_train",
                                   top_ngram_percentile=5,
                                   ranking_algorithm='random_forest',
                                   ranking_n_estimators=100,
                                   rel_regularization_C=1.0,
                                   extract_text_features_pruning=False,
                                   extract_text_features_ranking=True,
                                   extract_cqa_features_ranking=True,
                                   extract_cqa_features_pruning=False,
                                   use_pruning=True),
                  ranker.AccuModel('WQ_Ranker_WithCqaRank_RF100_Dev',
                                   "webquestions_split_train",
                                   top_ngram_percentile=5,
                                   ranking_algorithm='random_forest',
                                   ranking_n_estimators=100,
                                   rel_regularization_C=1.0,
                                   extract_text_features_pruning=False,
                                   extract_text_features_ranking=False,
                                   extract_cqa_features_ranking=True,
                                   extract_cqa_features_pruning=False,
                                   use_pruning=True),

                  ranker.AccuModel('WQ_Ranker_WithTextCqaPruneRank_RF300_Dev',
                                   "webquestions_split_train",
                                   top_ngram_percentile=5,
                                   ranking_algorithm='random_forest',
                                   ranking_n_estimators=300,
                                   rel_regularization_C=1.0,
                                   extract_text_features_pruning=True,
                                   extract_text_features_ranking=True,
                                   extract_cqa_features_ranking=True,
                                   extract_cqa_features_pruning=True,
                                   extract_clueweb_features_pruning=False,
                                   extract_clueweb_features_ranking=False,
                                   use_pruning=True),
                  ranker.AccuModel('WQ_Ranker_WithTextCqaCluewebPruneRank_RF300_Dev',
                                   "webquestions_split_train",
                                   top_ngram_percentile=5,
                                   ranking_algorithm='random_forest',
                                   ranking_n_estimators=300,
                                   rel_regularization_C=1.0,
                                   extract_text_features_pruning=True,
                                   extract_text_features_ranking=True,
                                   extract_cqa_features_ranking=True,
                                   extract_cqa_features_pruning=True,
                                   extract_clueweb_features_pruning=True,
                                   extract_clueweb_features_ranking=True,
                                   use_pruning=True),

                  ranker.AccuModel('WQ_Ranker_WithTextCqaCluewebPruneRank_DateRange_RF300',
                                   "webquestions_train_externalentities_all_daterange",
                                   top_ngram_percentile=5,
                                   ranking_algorithm='random_forest',
                                   ranking_n_estimators=300,
                                   rel_regularization_C=1.0,
                                   extract_text_features_pruning=True,
                                   extract_text_features_ranking=True,
                                   extract_cqa_features_ranking=True,
                                   extract_cqa_features_pruning=True,
                                   extract_clueweb_features_pruning=True,
                                   extract_clueweb_features_ranking=True,
                                   use_pruning=True),
                  ranker.AccuModel('WQ_Ranker_WithTextCqaCluewebPruneRank_DateRange_RF300_Dev',
                                   "webquestions_split_train_externalentities_all_daterange",
                                   top_ngram_percentile=5,
                                   ranking_algorithm='random_forest',
                                   ranking_n_estimators=300,
                                   rel_regularization_C=1.0,
                                   extract_text_features_pruning=True,
                                   extract_text_features_ranking=True,
                                   extract_cqa_features_ranking=True,
                                   extract_cqa_features_pruning=True,
                                   extract_clueweb_features_pruning=True,
                                   extract_clueweb_features_ranking=True,
                                   use_pruning=True),


                  ranker.AccuModel('WQ_Ranker_WithTextCqaPruneRank_ExtExtAll_RF300_Dev',
                                   "webquestions_split_train_externalentities_all",
                                   top_ngram_percentile=5,
                                   ranking_algorithm='random_forest',
                                   ranking_n_estimators=300,
                                   rel_regularization_C=1.0,
                                   extract_text_features_pruning=True,
                                   extract_text_features_ranking=True,
                                   extract_cqa_features_ranking=True,
                                   extract_cqa_features_pruning=True,
                                   extract_clueweb_features_pruning=False,
                                   extract_clueweb_features_ranking=False,
                                   use_pruning=True),

                  ranker.AccuModel('WQ_Ranker_WithTextCqaRank_ExtExtAll_RF1000_Dev',
                                   "webquestions_split_train_externalentities_all",
                                   top_ngram_percentile=5,
                                   ranking_algorithm='random_forest',
                                   ranking_n_estimators=1000,
                                   rel_regularization_C=1.0,
                                   extract_text_features_pruning=False,
                                   extract_text_features_ranking=True,
                                   extract_cqa_features_pruning=False,
                                   extract_cqa_features_ranking=True,
                                   extract_clueweb_features_pruning=False,
                                   extract_clueweb_features_ranking=False,
                                   use_pruning=True),
                  ranker.AccuModel('WQ_Ranker_WithTextCqaPruneRank_ExtExtAll_RF1000_Dev',
                                   "webquestions_split_train_externalentities_all",
                                   top_ngram_percentile=5,
                                   ranking_algorithm='random_forest',
                                   ranking_n_estimators=1000,
                                   rel_regularization_C=1.0,
                                   extract_text_features_pruning=True,
                                   extract_text_features_ranking=True,
                                   extract_cqa_features_ranking=True,
                                   extract_cqa_features_pruning=True,
                                   extract_clueweb_features_pruning=False,
                                   extract_clueweb_features_ranking=False,
                                   use_pruning=True),
                  ranker.AccuModel('WQ_Ranker_WithTextCqaPruneRank_ExtExtAll_GBT1000_Dev',
                                   "webquestions_split_train_externalentities_all",
                                   top_ngram_percentile=5,
                                   ranking_algorithm='gbt',
                                   ranking_n_estimators=1000,
                                   rel_regularization_C=1.0,
                                   extract_text_features_pruning=True,
                                   extract_text_features_ranking=True,
                                   extract_cqa_features_ranking=True,
                                   extract_cqa_features_pruning=True,
                                   extract_clueweb_features_pruning=False,
                                   extract_clueweb_features_ranking=False,
                                   use_pruning=True),

                  ranker.AccuModel('WQ_Ranker_WithTextCqaPruneRank_RF100_ExtEnt3',
                                   "webquestions_split_train_externalentities3",
                                   top_ngram_percentile=5,
                                   ranking_algorithm='random_forest',
                                   ranking_n_estimators=100,
                                   rel_regularization_C=1.0,
                                   extract_text_features_pruning=True,
                                   extract_text_features_ranking=True,
                                   extract_cqa_features_ranking=True,
                                   extract_cqa_features_pruning=True,
                                   use_pruning=True),


                   # -------------------------------------------------------------
                   # Here is my main model for now!
                   ranker.AccuModel('WQ_Ranker_WithTextPruneRank_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=True,
                                     extract_text_features_ranking=True,
                                     use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_WithTextRank_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     rel_regularization_C=1.0,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=True,
                                     use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_WithTextRank_RF1000_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     rel_regularization_C=1.0,
                                     ranking_n_estimators=1000,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=True,
                                     use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_WithTextRank_GBT1000_Dev',
                                     "webquestions_split_train",
                                     top_ngram_percentile=5,
                                     rel_regularization_C=1.0,
                                     ranking_algorithm='gbt',
                                     ranking_n_estimators=1000,
                                     extract_text_features_pruning=False,
                                     extract_text_features_ranking=True,
                                     use_pruning=True),

                   ranker.AccuModel('WQ_Ranker_small',
                                    "webquestions_small_test",
                                    top_ngram_percentile=5,
                                    rel_regularization_C=1.0,
                                    extract_text_features_ranking=False,
                                    extract_text_features_pruning=False,
                                    extract_cqa_features_pruning=False,
                                    extract_cqa_features_ranking=False,
                                    extract_clueweb_features_pruning=False,
                                    extract_clueweb_features_ranking=False,
                                    use_pruning=True),
                   ranker.AccuModel('WQ_Ranker_WithText_WithCqa_small',
                                    "webquestions_small_train",
                                    top_ngram_percentile=5,
                                    rel_regularization_C=1.0,
                                    extract_text_features_ranking=False,
                                    extract_text_features_pruning=False,
                                    extract_cqa_features_pruning=False,
                                    extract_cqa_features_ranking=False,
                                    extract_clueweb_features_pruning=True,
                                    extract_clueweb_features_ranking=True,
                                    use_pruning=True),
                   ranker.SimpleScoreRanker('SimpleRanker'),
                   ranker.SimpleScoreRanker('SimpleRanker_entity_oracle',
                                             entity_oracle_file=free917_entities),
                   ranker.LiteralRanker('LiteralRanker'),
                   ranker.LiteralRanker('LiteralRanker_entity_oracle',
                                         entity_oracle_file=free917_entities),
                   ]

    # A dictionary used for lookup via scorer name.
    scorers_dict = OrderedDict(
        [(s.name, s) for s in scorer_list]
    )

    # A dict of dataset name and file.
    DATASETS = OrderedDict(
        [('free917train',
          'evaluation-data/'
          'free917.train.json'),
         ('webquestionstrain',
          'evaluation-data/'
          'webquestions.train.json'),
         ('free917train_1of2',
          'evaluation-data/'
          'free917.train_1of2.json'),
         ('free917train_2of2',
          'evaluation-data/'
          'free917.train_2of2.json'),
         ('webquestionstrain_1of2',
          'evaluation-data/'
          'webquestions.train_1of2.json'),
         ('webquestionstrain_1of2_1of2',
          'evaluation-data/'
          'webquestions.train_1of2_1of2.json'),
         ('webquestionstrain_1of2_2of2',
          'evaluation-data/'
          'webquestions.train_1of2_2of2.json'),
         ('webquestionstrain_2of2',
          'evaluation-data/'
          'webquestions.train_2of2.json'),
         ('free917test',
          'evaluation-data/'
          'free917.test.json'),
         ('webquestionstest',
          'evaluation-data/'
          'webquestions.test.json'),
         ('free917test_graphparser',
          'evaluation-data/'
          'free917.test_graphparser.json'),
         ('webquestionstest_graphparser',
          'evaluation-data/'
          'webquestions.test_graphparser.json'),
         ('webquestionstrain_graphparser',
          'evaluation-data/'
          'webquestions.train_graphparser.json'),
         ('webquestions_small_train',
          'evaluation-data/'
          'webquestions.train_small.json'),
         ('webquestions_small_test',
          'evaluation-data/'
          'webquestions.test_small.json'),
         ('webquestions_split_train',
          'evaluation-data/'
          'webquestions.split.train.json'),
         ('webquestions_split_dev',
          'evaluation-data/'
          'webquestions.split.dev.json'),
         ('webquestions_train_externalentities',
          'evaluation-data/'
          'webquestions.train.extent.json'),
         ('webquestions_test_externalentities',
          'evaluation-data/'
          'webquestions.test.extent.json'),
         ('webquestions_train_externalentities3',
          'evaluation-data/'
          'webquestions.train.extent3.json'),
         ('webquestions_test_externalentities3',
          'evaluation-data/'
          'webquestions.test.extent3.json'),

         ('webquestions_split_train_externalentities',
          'evaluation-data/'
          'webquestions.split.train.extent.json'),
         ('webquestions_split_dev_externalentities',
          'evaluation-data/'
          'webquestions.split.dev.extent.json'),


         ('webquestions_split_train_externalentities3',
          'evaluation-data/'
          'webquestions.split.train.extent3.json'),
         ('webquestions_split_dev_externalentities3',
          'evaluation-data/'
          'webquestions.split.dev.extent3.json'),

         ('webquestions_split_train_externalentities_all',
          'evaluation-data/'
          'webquestions.split.train.extent_all.json'),
         ('webquestions_split_dev_externalentities_all',
          'evaluation-data/'
          'webquestions.split.dev.extent_all.json'),
         ('webquestions_train_externalentities_all',
          'evaluation-data/'
          'webquestions.train.extent_all.json'),
         ('webquestions_test_externalentities_all',
          'evaluation-data/'
          'webquestions.test.extent_all.json'),

         # Train and test with external entities and extra date range templates
         ('webquestions_train_externalentities_all_daterange',
          'evaluation-data/'
          'webquestions.train.extent_all_daterange.json'),
         ('webquestions_test_externalentities_all_daterange',
          'evaluation-data/'
          'webquestions.test.extent_all_daterange.json'),
         ('webquestions_split_train_externalentities_all_daterange',
          'evaluation-data/'
          'webquestions.split.train.extent_all_daterange.json'),
         ('webquestions_split_dev_externalentities_all_daterange',
          'evaluation-data/'
          'webquestions.split.dev.extent_all_daterange.json'),



         ('webquestions_split_train_daterange',
          'evaluation-data/'
          'webquestions.split.train.daterange.json'),
         ('webquestions_split_dev_daterange',
          'evaluation-data/'
          'webquestions.split.dev.daterange.json'),

         ('webquestions_split_train_typefilter',
          'evaluation-data/'
          'webquestions.split.train.typefilter.json'),
         ('webquestions_split_dev_typefilter',
          'evaluation-data/'
          'webquestions.split.dev.typefilter.json'),


         ('webquestions_test_filter',
          'evaluation-data/'
          'webquestions.test_for_filter.json')
         ]
    )
