import os

import cPickle as pickle

from gensim import matutils

import globals
import gzip
from math import log
import numpy as np

import logging

from entity_linker.entity_linker import KBEntity
from text2kb.utils import tokenize, avg, get_embeddings

logger = logging.getLogger(__name__)

_clueweb_entitypairs_langmodel = None
_clueweb_entitypairs_embeddings = None

webquestions_term_set = {u'trenton', u'ainge', u'allama', u'joyner', u'implants', u'colleges', u'four', u'1869',
                         u'coopers', u'woods', u'asian', u'woody', u'captain', u'hate', u'elaines', u'founder',
                         u'paris', u'davids', u'theodore', u'fergusons', u'alf', u'wilsons', u'edward', u'kidman',
                         u'under', u'dukes', u'worth', u'schalke', u'plants', u'avril', u'stanton', u'dominate',
                         u'cavaliers', u'aurora', u'rise', u'dell', u'hummel', u'montel', u'berkowitz', u'bernall',
                         u'wilfred', u'jack', u'govern', u'jacob', u'stabbed', u'disneys', u'yuvraj', u'whoopi',
                         u'school', u'shays', u'sampson', u'leeuwenhoek', u'companies', u'herbert', u'nigerians',
                         u'monsanto', u'burke', u'smoky', u'venus', u'ups', u'jamaica', u'force', u'vladimir',
                         u'miller', u'danneel', u'rodman', u'bacon', u'japanese', u'horn', u'chef', u'second',
                         u'street', u'summer', u'pattinson', u'huell', u'7th', u'sailed', u'air', u'seusss', u'blue',
                         u'established', u'liam', u'christ', u'organisms', u'inglewood', u'cyprus', u'panama',
                         u'rockies', u'circle', u'asia', u'dinozzo', u'haze', u'causes', u'conduct', u'new',
                         u'officially', u'disney', u'viii', u'helmets', u'meg', u'crouch', u'dahl', u'zach',
                         u'kowalski', u'hera', u'men', u'drew', u'bangkok', u'beck', u'pratt', u'china', u'kicker',
                         u'102', u'affiliated', u'100', u'101', u'tatum', u'baldy', u'romans', u'luther', u'kids',
                         u'daughter', u'vikings', u'jordison', u'study', u'pennsylvanias', u'gymnast', u'kidd', u'omar',
                         u'chrysler', u'deere', u'military', u'montesquie', u'joshua', u'golden', u'invasion',
                         u'besides', u'campaign', u'wikimedia', u'julie', u'reagan', u'julia', u'county', u'franz',
                         u'geico', u'stern', u'eastwood', u'mvp', u'heathrow', u'sarah', u'hillsborough', u'commonly',
                         u'charge', u'assyrians', u'portugal', u'would', u'army', u'hospital', u'indians', u'chargers',
                         u'pudge', u'bike', u'call', u'dialects', u'spike', u'deville', u'indiana', u'waynoka', u'type',
                         u'barry', u'owen', u'holy', u'nemo', u'oscar', u'jordyn', u'wars', u'reign', u'democritus',
                         u'melba', u'connecticut', u'championships', u'former', u'lord', u'hold', u'shockey', u'tampa',
                         u'pulitzer', u'me', u'shepherds', u'1993', u'word', u'wore', u'mc', u'henri', u'1999', u'1998',
                         u'mn', u'eclipse', u'theories', u'movies', u'navajo', u'rim', u'henry', u'ernest', u'carmen',
                         u'gloria', u'boyfriend', u'wand', u'give', u'collegehumor', u'india', u'charlton', u'currency',
                         u'indies', u'woman', u'walsh', u'british', u'want', u'david', u'seacrest', u'ceremony',
                         u'clayburgh', u'colosseum', u'end', u'dorothea', u'tchaikovsky', u'niemann', u'travel',
                         u'soros', u'bowls', u'how', u'louisville', u'writers', u'ethnicity', u'rookie', u'parana',
                         u'beach', u'ronnie', u'flickerman', u'raleigh', u'dialect', u'merritt', u'elizabeth', u'after',
                         u'scottsdale', u'serbian', u'wrong', u'shaq', u'features', u'midlands', u'president',
                         u'frusciante', u'humphrey', u'types', u'slavery', u'vera', u'nagasaki', u'sioux', u'rudolf',
                         u'colfer', u'headquarters', u'harley', u'greek', u'green', u'chers', u'enter', u'lindbergh',
                         u'operate', u'athletes', u'order', u'douglass', u'lindsay', u'senators', u'helens',
                         u'delaware', u'office', u'concertos', u'cornwallis', u'over', u'confederate', u'gettysburg',
                         u'klum', u'murray', u'jerry', u'jews', u'ibanez', u'london', u'oswald', u'japan', u'owens',
                         u'colorados', u'before', u'chatta', u'shawnee', u'maricopa', u'kaepernick', u'christie',
                         u'denver', u'writing', u'fade', u'jenni', u'wales', u'probst', u'chapel', u'pass', u'okeeffe',
                         u'electra', u'then', u'aston', u'iowa', u'tourist', u'glastonbury', u'deathly', u'break',
                         u'band', u'bang', u'hernando', u'they', u'schools', u'eisenhower', u'bank', u'prize',
                         u'represents', u'germanic', u'netherlands', u'alex', u'rocky', u'bosnia', u'debut',
                         u'arrested', u'l', u'detroit', u'herald', u'conflict', u'lauer', u'each', u'garten',
                         u'volcano', u'went', u'bells', u'rosemary', u'side', u'carlos', u'mean', u'angola',
                         u'telescope', u'concord', u'diana', u'series', u'allan', u'january', u'skins', u'milan',
                         u'taught', u'trading', u'efron', u'navy', u'anthem', u'dawn', u'truman', u'saturday',
                         u'declaration', u'cromwells', u'network', u'driving', u'oprah', u'fiji', u'views', u'urbana',
                         u'bennet', u'mason', u'monta', u're', u'jong', u'daniel', u'carthage', u'got', u'newly',
                         u'hookes', u'venezuela', u'ella', u'independence', u'foundation', u'arizona', u'josef',
                         u'lawless', u'revenge', u'free', u'fred', u'thieves', u'frey', u'management', u'mavericks',
                         u'amadeus', u'sandra', u'egyptians', u'amerigo', u'heat', u'harriet', u'renee', u'perform',
                         u'jabbar', u'created', u'days', u'local', u'shakur', u'fleck', u'fought', u'baltic',
                         u'stewart', u'rand', u'industrial', u'niccolo', u'characters', u'nhl', u'avett', u'birch',
                         u'primary', u'maldives', u'seinfeld', u'hoon', u'kfc', u'another', u'cher', u'langston',
                         u'kia', u'hood', u'timothy', u'toy', u'hagman', u'groban', u'top', u'mcgee', u'xin', u'master',
                         u'too', u'xiv', u'tom', u'influence', u'gilbert', u'john', u'hewitt', u'danish', u'1948',
                         u'wizard', u'geneva', u'mechanism', u'centered', u'sparta', u'azle', u'convention', u'albert',
                         u'took', u'direct', u'neesons', u'scorpions', u'western', u'helen', u'lyndon', u'walnut',
                         u'eastman', u'kennedys', u'character', u'toronto', u'tonkin', u'trek', u'target', u'dawkins',
                         u'princeton', u'immigrants', u'tree', u'royal', u'shackleton', u'nations', u'bethany',
                         u'boulanger', u'invention', u'hadrian', u'historical', u'charlie', u'jerseys', u'powers',
                         u'stacey', u'namath', u'bridge', u'youre', u'palace', u'keyshia', u'ran', u'boston', u'modern',
                         u'raj', u'joakim', u'paraguay', u'leafs', u'obamas', u'lautner', u'lbj', u'spade', u'ray',
                         u'affairs', u'scriptures', u'laden', u'1964', u'responsible', u'snow', u'brandon', u'costello',
                         u'pittsburgh', u'morristown', u'materials', u'derek', u'rider', u'quarterback', u'rasheed',
                         u'bethune', u'bubles', u'philadelphia', u'lion', u'shall', u'bruce', u'iceland', u'clapton',
                         u'mother', u'victoria', u'mario', u'germany', u'bulldogs', u'organization', u'tsonga',
                         u'marie', u'tibetan', u'alabama', u'boudicca', u'maria', u'bradford', u'singer', u'don',
                         u'rogers', u'released', u'rancic', u'doc', u'spurrier', u'camp', u'flow', u'dog', u'falconeri',
                         u'spencer', u'slipknot', u'curie', u'points', u'tech', u'ibiza', u'thunder', u'voting',
                         u'sunbeam', u'dow', u'came', u'kristen', u'pope', u'hunger', u'lewis', u'effy', u'retire',
                         u'teresa', u'bonnie', u'nominated', u'religions', u'colors', u'qaeda', u'madeira',
                         u'somerhalder', u'halpert', u'hungary', u'nevada', u'capitol', u'orleans', u'faure',
                         u'northeast', u'dessen', u'wikianswers', u'claude', u'explain', u'minnesota', u'mens',
                         u'rihanna', u'rico', u'bush', u'oday', u'rick', u'aldi', u'gideon', u'announce', u'pickens',
                         u'rice', u'sedona', u'rica', u'do', u'exports', u'kaka', u'de', u'stop', u'dc', u'cardinals',
                         u'da', u'amazon', u'louverture', u'christopher', u'gogh', u'carries', u'haiti', u'dr',
                         u'barlow', u'peyton', u'uhura', u'pearson', u'gareth', u'countries', u'leif', u'howser',
                         u'bay', u'greene', u'grammer', u'bad', u'erupt', u'tebows', u'kauai', u'bashar', u'ruins',
                         u'secretary', u'blackwell', u'winslet', u'perrette', u'dobrev', u'pfeiffer', u'kunis',
                         u'kellan', u'testing', u'neeson', u'stewie', u'cabots', u'facts', u'fascists', u'shoreditch',
                         u'hagar', u'aires', u'activities', u'hammer', u'best', u'kovu', u'pete', u'smallville',
                         u'capone', u'oceania', u'spains', u'04', u'narrated', u'away', u'sail', u'wikipedia',
                         u'sweden', u'lott', u'xvi', u'future', u'olympics', u'lose', u'mum', u'farley', u'discovery',
                         u'deferred', u'we', u'wa', u'jose', u'1945', u'duggars', u'cavalier', u'inaba', u'boss',
                         u'mazda', u'wv', u'vernon', u'eli', u'wear', u'herbstreit', u'motto', u'clemson', u'newt',
                         u'mayoral', u'welchs', u'akkadian', u'aristotles', u'unicef', u'met', u'meredith', u'country',
                         u'nineveh', u'ncaa', u'pitt', u'against', u'orwell', u'players', u'acadia', u'games',
                         u'followill', u'normandy', u'brad', u'wipeout', u'studio', u'contribution', u'antoni', u'los',
                         u'libyan', u'diocletian', u'monae', u'2nd', u'karen', u'massive', u'knossos', u'quinn',
                         u'basque', u'tony', u'springs', u'jays', u'hitler', u'speak', u'barack', u'belize', u'sam',
                         u'afrikaans', u'source', u'union', u'buffett', u'three', u'been', u'cyrus', u'twain',
                         u'mcveigh', u'much', u'wyman', u'stadium', u'basic', u'crawfish', u'entered', u'hitlers',
                         u'michele', u'idol', u'ellington', u'website', u'life', u'tucson', u'families', u'homeland',
                         u'tigris', u'eastern', u'drugs', u'baum', u'republicans', u'irving', u'darfur', u'irvine',
                         u'dave', u'harrelson', u'chile', u'child', u'catch', u'zack', u'lionel', u'johansson',
                         u'baggins', u'macfarlane', u'maryville', u'sculpt', u'oher', u'fallon', u'originate',
                         u'lavoisier', u'kentucky', u'n', u'turners', u'near', u'kepler', u'depp', u'malayalam',
                         u'voice', u'davenport', u'k', u'kuti', u'veronica', u'seven', u'pyramid', u'uganda', u'mexico',
                         u'ip', u'is', u'speech', u'it', u'defeated', u'audrey', u'burundi', u'australia', u'il', u'in',
                         u'ia', u'madonna', u'farsi', u'seattle', u'mouse', u'turner', u'if', u'champlain', u'hong',
                         u'tecumseh', u'nike', u'journal', u'things', u'make', u'bella', u'rebellion', u'beside',
                         u'descend', u'babies', u'thalys', u'agatha', u'colonies', u'dunkirk', u'cuoco', u'bunny',
                         u'yusuf', u'european', u'hank', u'voyages', u'abolition', u'sings', u'welsh', u'sacramento',
                         u'everett', u'quentin', u'hang', u'speakers', u'elle', u'renaissance', u'sacraments', u'kim',
                         u'jeffersons', u'hans', u'tyson', u'gaudi', u'kid', u'dylan', u'practiced', u'aladdin',
                         u'smokey', u'kyla', u'koreas', u'neptune', u'1971', u'ocean', u'more', u'rome', u'ufc',
                         u'reese', u'capwell', u'90210', u'romo', u'the', u'corporate', u'musical', u'dads', u'left',
                         u'gilda', u'unified', u'sheens', u'traditions', u'just', u'gods', u'warmest', u'newton',
                         u'eight', u'palpatine', u'identify', u'hangover', u'picasso', u'campbell', u'afellay',
                         u'stacys', u'portrayed', u'kroy', u'nicolas', u'biome', u'polos', u'broncos', u'adidas',
                         u'1773', u'yamaha', u'cornell', u'cherry', u'josh', u'clarksville', u'woodstock',
                         u'jacksonville', u'jules', u'wright', u'jefferson', u'board', u'justices', u'prison',
                         u'basketball', u'has', u'rajya', u'dubinsky', u'desire', u'donnie', u'maya', u'jana',
                         u'vanessa', u'egfr', u'online', u'burne', u'arab', u'posey', u'beecher', u'bushs', u'latifah',
                         u'newcastle', u'judge', u'cape', u'burns', u'apart', u'constitution', u'brought', u'cooley',
                         u'bobby', u'clegg', u'hunt', u'orlando', u'alice', u'tebow', u'steinem', u'alamo', u'cayman',
                         u'offices', u'gandhi', u'night', u'security', u'sebastian', u'ennis', u'iroquois', u'webb',
                         u'portuguese', u'pauley', u'right', u'dean', u'trained', u'crowe', u'czech', u'51', u'samui',
                         u'dead', u'jennifer', u'wwe', u'born', u'donald', u'hoover', u'usher', u'election', u'lions',
                         u'hemsworth', u'bora', u'kakadu', u'christiaan', u'friend', u'cooper', u'abuse', u'for',
                         u'purple', u'establish', u'twains', u'ukrainian', u'fox', u'arthur', u'bruins', u'caribbean',
                         u'shakespeare', u'savile', u'christmas', u'pagans', u'schleiden', u'core', u'columbus', u'who',
                         u'ww1', u'bold', u'ww2', u'lucille', u'burn', u'buenaventura', u'ina', u'popular',
                         u'hutcherson', u'graduated', u'khan', u'bangalore', u'falls', u'super', u'meyer', u'trophy',
                         u'chilean', u'taurasi', u'mcgwire', u'riveras', u'obi', u'dollars', u'hutchinson', u'bynum',
                         u'o', u'wentworth', u'magazine', u'coronado', u'islands', u'nixon', u'duke', u'raised',
                         u'coins', u'whats', u'shenandoah', u'lenin', u'civil', u'pays', u'marshall', u'sergio',
                         u'attorney', u'lois', u'sherrod', u'greenland', u'daud', u'osment', u'amsterdam', u'nixons',
                         u'creek', u'wan', u'fredricksen', u'deception', u'malcom', u'medal', u'people', u'satriani',
                         u'fight', u'virgin', u'anderson', u'joseph', u'winning', u'author', u'way', u'aurelio',
                         u'music', u'bolivia', u'was', u'war', u'tamu', u'lowest', u'head', u'medium', u'iceplex',
                         u'form', u'offer', u'batman', u'corleone', u'leias', u'ford', u'peninsula', u'buckingham',
                         u'hemisphere', u'augustine', u'uncle', u'granger', u'universitys', u'surrender', u'fort',
                         u'drita', u'pavilion', u'friday', u'braves', u'la', u'mtv', u'clubs', u'epps', u'whiskey',
                         u'plymouth', u'riley', u'yucatan', u'carey', u'vatican', u'palm', u'daddy', u'perks',
                         u'seneca', u'qin', u'liberal', u'gretzky', u'barrymore', u'minaj', u'angelou', u'tournament',
                         u'everest', u'tosh', u'miro', u'timezone', u'ship', u'magellan', u'ericsson', u'marys',
                         u'cassie', u'jodelle', u'palestinian', u'nj', u'nc', u'when', u'ne', u'cambodia', u'power',
                         u'tim', u'republic', u'roatan', u'giovanni', u'test', u'jenkins', u'falkland', u'tia', u'nv',
                         u'nafta', u'ike', u'brothers', u'phoenix', u'models', u'why', u'football', u'mcleod', u'yahoo',
                         u'walton', u'devon', u'invested', u'award', u'iceni', u'acted', u'weekend', u'senior', u'died',
                         u'began', u'jones', u'happening', u'excuse', u'australians', u'hemingway', u'santorum',
                         u'flag', u'ottawa', u'phoenician', u'vietnam', u'rastafarians', u'songz', u'time', u'howe',
                         u'letter', u'paige', u'aviano', u'songs', u'azaria', u'camacho', u'coach', u'cincinnati',
                         u'ron', u'rob', u'resources', u'rod', u'bombed', u'invent', u'laura', u'roy', u'manager',
                         u'marion', u'mila', u'battle', u'playoffs', u'hinton', u'milk', u'roanoke', u'venice',
                         u'mayan', u'zone', u'technique', u'father', u'1944', u'menace', u'oldest', u'cheat',
                         u'earthquake', u'oz', u'face', u'text', u'dartmouth', u'macho', u'goodyear', u'ride',
                         u'southwest', u'rebecca', u'brown', u'kundra', u'federation', u'md', u'hannah', u'saldana',
                         u'ibrahim', u'ewell', u'mccartneys', u'cook', u'join', u'zito', u'timor', u'heston', u'percy',
                         u'leeds', u'hour', u'did', u'die', u'philippines', u'1996', u'hawaii', u'edgar', u'temple',
                         u'leave', u'p', u'holliday', u'defaults', u'team', u'manchester', u'guy', u'teenager',
                         u'round', u'lloyd', u'olympic', u'revolution', u'hell', u'villa', u'collage', u'bravo',
                         u'discover', u'literature', u'sign', u'horror', u'invaded', u'liszt', u'alfs', u'hazzard',
                         u'anasazi', u'langmuir', u'port', u'sacrifices', u'afghanistan', u'elton', u'stands', u'mt',
                         u'celebrated', u'current', u'grover', u'lennon', u'somalia', u'international', u'belsen',
                         u'ivory', u'tiberius', u'nasri', u'drafted', u'angelina', u'dewan', u'evolved', u'mali',
                         u'lange', u'vanderbilt', u'french', u'lakes', u'water', u'giles', u'chilton', u'baseball',
                         u'redskins', u'groups', u'address', u'galileo', u'teacher', u'galilei', u'alto', u'winona',
                         u'mubarak', u'canadian', u'madden', u'my', u'lancaster', u'lakers', u'mauritius',
                         u'accomplished', u'galifianakis', u'descended', u'franklin', u'christchurch', u'sawa', u't20',
                         u'bob', u'myers', u'rafael', u'montreal', u'churchill', u'retired', u'stockton', u'aidan',
                         u'sri', u'harding', u'credited', u'important', u'lucas', u'prefer', u'shark', u'bloody',
                         u'italians', u'patriots', u'buble', u'compete', u'shelley', u'schenectady', u'crisis',
                         u'market', u'hotels', u'schwann', u'ayn', u'saki', u'franco', u'jemaine', u'roma', u'visit',
                         u'athens', u'angela', u'fairfield', u'territories', u'live', u'vicksburg', u'andy', u'peru',
                         u'calgary', u'australian', u'prep', u'today', u'chapter', u'pavlov', u'kerry', u'club',
                         u'vaders', u'phillies', u'inventions', u'oregon', u'steffy', u'downtown', u'sierra',
                         u'primarily', u'vmas', u'mansfield', u'far', u'hallows', u'amelia', u'cases', u'given',
                         u'soldiers', u'mascot', u'fly', u'organizations', u'judi', u'pageant', u'slogan', u'spinelli',
                         u'gregoire', u'car', u'originally', u'dmitri', u'soul', u'vito', u'heskey', u'reviews',
                         u'judy', u'regions', u'can', u'cam', u'kendrick', u'fla', u'terrell', u'german', u'goodall',
                         u'pretoria', u'plum', u'rufus', u'spy', u'crazy', u'citizens', u'trump', u'kenneth',
                         u'downfall', u'predict', u'december', u'winston', u'nascar', u'death', u'celsius', u'chin',
                         u'gogol', u'council', u'allowed', u'235', u'latimore', u'occur', u'ferdinand', u'pink',
                         u'lavaca', u'bigos', u'lombardi', u'alagaesia', u'oslo', u'babylonians', u'means', u'berlin',
                         u'antoine', u'write', u'ryder', u'rubio', u'wsop', u'vancouver', u'nyc', u'coleman', u'speaks',
                         u'sworn', u'revolted', u'economy', u'map', u'spielberg', u'fascist', u'overstreet', u'snl',
                         u'southern', u'raiders', u'islamic', u'jaguars', u'produce', u'designed', u'date', u'heroes',
                         u'guys', u'grow', u'pistorius', u'7', u'natural', u'omen', u'johnson', u'ss', u'coretta',
                         u'bonaparte', u'st', u'tale', u'burmese', u'jail', u'chavez', u'african', u'title', u'kurt',
                         u'jacques', u'sf', u'talk', u'tomlin', u'shoes', u'canberra', u'east', u'daiichi', u'beaumont',
                         u'mainly', u'kong', u'kony', u'eriksons', u'experiments', u'pitch', u'fegans', u'peterson',
                         u'cole', u'blart', u'worship', u'sistine', u'grammy', u'accepted', u'1831', u'group',
                         u'wallace', u'willow', u'rottweiler', u'jim', u'oakley', u'jiu', u'cheyenne', u'saxon',
                         u'mckinley', u'hanks', u'main', u'norway', u'into', u'texas', u'happened', u'johns', u'buenos',
                         u'3', u'moms', u'granville', u'adopted', u'krueger', u'nation', u'jaworski', u'1991', u'hale',
                         u'base', u'nov', u'now', u'twilight', u'hall', u'cliff', u'term', u'name', u'james',
                         u'hancock', u'brody', u'spudd', u'boehner', u'ussr', u'viggo', u'rock', u'draper', u'quarter',
                         u'revere', u'el', u'republican', u'en', u'honduras', u'fired', u'latin', u'populated',
                         u'experiment', u'benito', u'kane', u'directing', u'indianapolis', u'bradley', u'electorate',
                         u'persian', u'ex', u'year', u'eu', u'dench', u'happen', u'taoism', u'minority', u'canada',
                         u'living', u'accomplish', u'jackson', u'opened', u'space', u'dwayne', u'oklahoma', u'rudd',
                         u'factory', u'generation', u'looking', u'stupid', u'shameless', u'stallone', u'dutch',
                         u'wainwright', u'darin', u'shows', u'burnett', u'metro', u'dodgers', u'theory', u'carr',
                         u'cars', u'madagascar', u'brooks', u'zuckerberg', u'tatyana', u'snooker', u'ackles',
                         u'california', u'carl', u'shi', u'brooke', u'obligation', u'e3', u'care', u'training',
                         u'esthers', u'language', u'amanda', u'washingtons', u'marlo', u'spending', u'gosling',
                         u'plane', u'place', u'gordon', u'think', u'first', u'origin', u'sanchez', u'romania',
                         u'tennis', u'saving', u'roswell', u'spoken', u'clause', u'potter', u'zac', u'ladainian',
                         u'one', u'kris', u'boleyn', u'americans', u'fast', u'directly', u'spanish', u'vote', u'ring',
                         u'open', u'george', u'city', u'little', u'ian', u'district', u'waite', u'lanka', u'bahamas',
                         u'subatomic', u'returns', u'2', u'draft', u'anakin', u'ringo', u'white', u'brees', u'williams',
                         u'fma', u'alps', u'sugihara', u'kohler', u'hub', u'that', u'shawn', u'season', u'moscow',
                         u'suit', u'todd', u'alan', u'steinbeck', u'jane', u'hillary', u'danny', u'macdonald',
                         u'shirley', u'thai', u'seat', u'keating', u'titans', u'10', u'13', u'nathan', u'seuss', u'16',
                         u'merrell', u'gobi', u'require', u'browning', u'hsbc', u'victorias', u'rehab', u'legacy',
                         u'were', u'southgate', u'xliv', u'russia', u'published', u'and', u'illness', u'san', u'angel',
                         u'mountains', u'craig', u'ann', u'greyhound', u'reno', u'voices', u'13th', u'medical', u'say',
                         u'wellsville', u'buried', u'voiced', u'allen', u'breakfast', u'nazi', u'calendar', u'marathon',
                         u'superman', u'nikola', u'zoe', u'alias', u'warriors', u'malta', u'zoo', u'holloway',
                         u'equipment', u'clearwater', u'cantor', u'take', u'thermometer', u'mayer', u'ericson',
                         u'becoming', u'channel', u'blackfoot', u'begin', u'frost', u'pain', u'roster', u'tornado',
                         u'sherman', u'microwaves', u'herschel', u'woodrow', u'blowers', u'assault', u'nolan',
                         u'skinner', u'connor', u'services', u'america', u'hardships', u'michelle', u'cuban',
                         u'democratic', u'lenny', u'considered', u'headed', u'phil', u'corwin', u'drive', u'wing',
                         u'elie', u'wind', u'slaves', u'cortez', u'atlantic', u'steffens', u'abraham', u'salt', u'axl',
                         u'laws', u'event', u'madison', u'shot', u'mohammed', u'beckham', u'show', u'morrissey',
                         u'ronaldinho', u'atom', u'discovered', u'hunnam', u'troy', u'executed', u'krabi', u'mexican',
                         u'mister', u'maine', u'help', u'mowry', u'sinks', u'laughlin', u'adolf', u'gulf', u'knicks',
                         u'romanian', u'tweddle', u'deck', u'saints', u'written', u'geographically', u'only', u'going',
                         u'black', u'hockey', u'nadia', u'chopin', u'thompson', u'caroline', u'boyle', u'carolina',
                         u'directed', u'atticus', u'beatles', u'hungarian', u'get', u'cannon', u'samuel', u'ramadan',
                         u'ali', u'hedge', u'trade', u'laguna', u'wahlberg', u'secondary', u'prime', u'well', u'sheryl',
                         u'prima', u'frampton', u'girl', u'artist', u'allman', u'hamilton', u'malaysian', u'experience',
                         u'alicia', u'scientist', u'roger', u'bobcats', u'miley', u'orioles', u'where', u'husband',
                         u'wiki', u'shoreview', u'declared', u'beethoven', u'ned', u'osbourne', u'eriksen', u'seas',
                         u'duggar', u'fe', u'ends', u'psych', u'up', u'huckabee', u'elected', u'1922', u'college',
                         u'sean', u'kermit', u'seal', u'stanley', u'surgery', u'sport', u'appear', u'israeli',
                         u'panthers', u'indicted', u'parent', u'1819', u'federal', u'harvey', u'josephs', u'shiva',
                         u'representatives', u'carradine', u'label', u'outside', u'pistons', u'between', u'import',
                         u'nathaniel', u'monarchy', u'jobs', u'august', u'habsburg', u'teddy', u'originated', u'marvin',
                         u'planes', u'tut', u'jacobs', u'jr', u'guitar', u'elijah', u'awards', u'armenian', u'jj',
                         u'mendeleev', u'nationality', u'cities', u'come', u'lopez', u'isthmus', u'jfk', u'warhol',
                         u'stages', u'rugby', u'libya', u'mona', u'ryanair', u'region', u'staffordshire', u'prompted',
                         u'mana', u'math', u'christmases', u'present', u'dated', u'kahlo', u'senator', u'traded',
                         u'stance', u'pakistan', u'arkwright', u'color', u'endless', u'colony', u'period', u'jerrod',
                         u'ii', u'grants', u'mongolia', u'polo', u'natively', u'poe', u'polk', u'nicole', u'moore',
                         u'turkey', u'jovan', u'sarabi', u'oliver', u'chad', u'howard', u'coleridge', u'selena',
                         u'atomic', u'airlines', u'mark', u'hutton', u'tesla', u'pujols', u'roald', u'tipton',
                         u'borders', u'marx', u'mary', u'holydays', u'educated', u'irans', u'cobain', u'gray',
                         u'bloomberg', u'hoffa', u'elvis', u'formed', u'andrew', u'laptops', u'stephen', u'minister',
                         u'penn', u'parrish', u'overdose', u'thing', u'presidency', u'weeks', u'standard', u'pilot',
                         u'sound', u'hughes', u'isabella', u'nogales', u'virchow', u'spiderman', u'mount', u'polls',
                         u'prominence', u'wiesels', u'arnold', u'hayes', u'overcome', u'many', u'newspaper',
                         u'blackhawks', u'pro', u'dumbledore', u'suzanne', u'ulysses', u'shepard', u'soil', u'j',
                         u'engaged', u'ellison', u'bros', u'destin', u'jitsu', u'tubman', u'radner', u'sahara',
                         u'kenya', u'property', u'fame', u'irene', u'movements', u'nat', u'different', u'develop',
                         u'doctor', u'harmon', u'alphabet', u'bowl', u's', u'ethiopia', u'cabot', u'wilhelm',
                         u'humphries', u'otto', u'propose', u'damon', u'physical', u'mallorca', u'wimbledon', u'berry',
                         u'week', u'noble', u'oil', u'bristol', u'closest', u'singapore', u'lymon', u'rimes', u'arctic',
                         u'riis', u'seyfried', u'cheers', u'hawkeye', u'album', u'harris', u'barber', u'freeview',
                         u'oersted', u'ira', u'cartoon', u'gingrich', u'atkins', u'costa', u'bryce', u'daytona',
                         u'pennsylvania', u'expression', u'constitutional', u'physics', u'crimean', u'glorious',
                         u'very', u'model', u'charbonneau', u'bettany', u'derrick', u'gates', u'peace', u'monet',
                         u'frankie', u'noah', u'being', u'money', u'speer', u'piazza', u'sights', u'bueller', u'elway',
                         u'tasmanian', u'kill', u'actor', u'harrison', u'touch', u'polish', u'colonise', u'baldwin',
                         u'barbados', u'wifes', u'yangtze', u'cancer', u'sheldon', u'ny', u'scissorhands', u'rose',
                         u'attractions', u'silver', u'blog', u'tunisia', u'perth', u'4', u'greenaway', u'dunham',
                         u'role', u'malcolm', u'ross', u'real', u'jake', u'around', u'zulu', u'read', u'shannen',
                         u'virginia', u'floods', u'amy', u'matlin', u'simmons', u'seahawks', u'mom', u'holly',
                         u'valvano', u'world', u'laos', u'luthor', u'ruled', u'denise', u'christina', u'macarthur',
                         u'adams', u'christine', u'kennedy', u'montesquieu', u'patrick', u'nissan', u'nigeria',
                         u'johann', u'thorpe', u'mathematician', u'tsunami', u'werner', u't', u'bewitched', u'clay',
                         u'beverly', u'served', u'inter', u'classified', u'mulder', u'buster', u'madrid', u'moving',
                         u'cathode', u'pacific', u'lucy', u'fukushima', u'eddie', u'cowboys', u'joan', u'thinks',
                         u'garnett', u'electrolux', u'1859', u'regina', u'kaiser', u'ellis', u'garland', u'colonial',
                         u'tube', u'scottie', u'legal', u'moon', u'buddha', u'belcher', u'phnom', u'willie', u'porter',
                         u'victory', u'londons', u'halliwells', u'wheat', u'business', u'airways', u'dali', u'plummer',
                         u'jennings', u'royals', u'volkswagen', u'1933', u'sports', u'jacksons', u'mandelas', u'raul',
                         u'thailand', u'francis', u'beaches', u'manufacturer', u'on', u'stone', u'quartermaine',
                         u'central', u'viiis', u'crabtree', u'hicks', u'natalee', u'island', u'industry', u'od',
                         u'brittany', u'eminems', u'gump', u'medicare', u'stand', u'west', u'joplin', u'financial',
                         u'backup', u'or', u'passchendaele', u'tribe', u'whitey', u'average', u'flemish', u'whites',
                         u'instruments', u'auschwitz', u'blessed', u'marlins', u'newtons', u'einstein', u'burton',
                         u'neil', u'gomez', u'bergen', u'sox', u'pirates', u'racquet', u'lakota', u'gunfight', u'her',
                         u'area', u'boyfriends', u'descendants', u'there', u'breyer', u'ponce', u'christianity',
                         u'start', u'lex', u'madisons', u'fela', u'ringwald', u'brazilian', u'dictator', u'djokovic',
                         u'goodman', u'catholics', u'leach', u'calabria', u'gibb', u'continents', u'mars', u'change',
                         u'seagal', u'corso', u'davy', u'gore', u'hurricanes', u'timons', u'walken', u'trying', u'with',
                         u'haitian', u'khloe', u'faster', u'laci', u'october', u'dna', u'dominican', u'harvick',
                         u'crawford', u'ronaldo', u'plaxico', u'freddy', u'escher', u'miguel', u'jamaican', u'adriana',
                         u'vick', u'witherspoon', u'gingrichs', u'beliefs', u'thicke', u'chaplin', u'illnesses',
                         u'taylor', u'johnny', u'turbines', u'arabs', u'mcentires', u'am', u'al', u'minneapolis', u'an',
                         u'deen', u'ap', u'britain', u'mekong', u'czechoslovakia', u'at', u'nero', u'logo',
                         u'girlfriend', u'politics', u'chowchilla', u'az', u'film', u'halen', u'verizon', u'nancy',
                         u'zelda', u'graduate', u'rubber', u'field', u'5', u'andres', u'2006', u'you', u'vince',
                         u'brandi', u'championship', u'congress', u'offensive', u'peat', u'carpathian', u'hawthorne',
                         u'dubuque', u'oracle', u'roxanne', u'adriatic', u'recent', u'massachusetts', u'terry',
                         u'chris', u'grimshaw', u'finals', u'alcohol', u'building', u'verrazano', u'wife', u'invest',
                         u'percentage', u'barcelona', u'raphael', u'corey', u'u', u'adam', u'boone', u'god',
                         u'starting', u'strings', u'mayans', u'represent', u'all', u'barone', u'senna', u'chinese',
                         u'anglican', u'messi', u'caused', u'landlocked', u'dollar', u'founded', u'received', u'childs',
                         u'cameron', u'follow', u'settlement', u'children', u'jerome', u'emily', u'particles',
                         u'griffin', u'bannatyne', u'coolidge', u'tx', u'fellowship', u'tv', u'incas', u'wyoming',
                         u'champions', u'tn', u'to', u'aaron', u'danielle', u'napoleon', u'malaysia', u'siblings',
                         u'set', u'hodgson', u'midwest', u'carters', u'mandela', u'ghana', u'case', u'esther',
                         u'jensen', u'egyptian', u'nobel', u'carolus', u'mockingbird', u'mexicos', u'megamind',
                         u'simpsons', u'sons', u'diary', u'husqvarna', u'fall', u'frankenstein', u'sony', u'elena',
                         u'kandinsky', u'leonidas', u'condition', u'syracuse', u'heaven', u'shania', u'cable', u'louis',
                         u'list', u'joined', u'large', u'sang', u'abenaki', u'mickelson', u'saudi', u'liars', u'harry',
                         u'lisa', u'blackout', u'maggie', u'dunk', u'population', u'wallflower', u'neighborhood',
                         u'andor', u'tea', u'ted', u'whens', u'cash', u'tex', u'dalton', u'rate', u'grease', u'design',
                         u'cornelia', u'nba', u'giza', u'situated', u'bass', u'gunn', u'90s', u'what', u'abe',
                         u'richard', u'clock', u'nana', u'sun', u'lawrence', u'skywalker', u'gatlinburg', u'sui',
                         u'jedi', u'diaz', u'issues', u'saruman', u'garth', u'leia', u'racing', u'public', u'deborah',
                         u'movement', u'schumacher', u'full', u'iran', u'theresa', u'answers', u'surfer', u'forlan',
                         u'wild', u'simon', u'jonas', u'andrews', u'palin', u'november', u'iraq', u'legend', u'loma',
                         u'bible', u'riviera', u'inspired', u'vietnamese', u'troops', u'jackie', u'through', u'okemos',
                         u'stella', u'airport', u'bulger', u'chipper', u'social', u'point', u'himym', u'alexandria',
                         u'hogg', u'family', u'barker', u'vii', u'africa', u'jehovah', u'halle', u'dirk', u'lagos',
                         u'jrr', u'appliances', u'crowned', u'simba', u'florence', u'niels', u'select', u'morrison',
                         u'silva', u'twa', u'sanjay', u'conferences', u'levine', u'niger', u'two', u'metallica',
                         u'steinbrenner', u'anger', u'niall', u'kimberly', u'seminole', u'6', u'taken', u'slater',
                         u'versailles', u'pixar', u'revolutionary', u'israel', u'diamond', u'chucky', u'company',
                         u'line', u'telephone', u'portman', u'germans', u'asheville', u'floyd', u'lleyton', u'known',
                         u'town', u'vp', u'salvador', u'middle', u'damien', u'science', u'roosevelt', u'flacco',
                         u'nina', u'mall', u'nebraska', u'hermione', u'morgan', u'novato', u'marc', u'treaty',
                         u'abrahamic', u'learn', u'beautiful', u'vivaldi', u'finland', u'texarkana', u'lerman',
                         u'division', u'rodriguez', u'greeley', u'share', u'staten', u'accept', u'finches', u'states',
                         u'biden', u'myles', u'niagara', u'numbers', u'sense', u'robinson', u'influenced', u'court',
                         u'clint', u'clarke', u'acts', u'hugh', u'conducted', u'alyson', u'browne', u'johannesburg',
                         u'perry', u'sacred', u'browns', u'plant', u'seoul', u'delonge', u'cancun', u'derived',
                         u'oilers', u'fa', u'fc', u'director', u'blood', u'maltese', u'mendel', u'skyfall', u'fl',
                         u'hirohito', u'a', u'planet', u'short', u'greenpeace', u'brady', u'susan', u'register',
                         u'hogarth', u'fulham', u'shore', u'mortensen', u'grande', u'hobbit', u'pay', u'banks',
                         u'wildwood', u'dream', u'playing', u'ncis', u'jordans', u'played', u'barnard',
                         u'administration', u'artwork', u'emmanuel', u'azerbaijan', u'auburn', u'held', u'logan',
                         u'scots', u'scott', u'uvm', u'bryans', u'thomson', u'milwaukee', u'mcdonalds', u'suffer',
                         u'its', u'ffa', u'islam', u'24', u'sharapova', u'style', u'hendrix', u'ayrton', u'22',
                         u'verne', u'pray', u'gerald', u'scully', u'resort', u'bermuda', u'dolly', u'pena',
                         u'toussaint', u'isaac', u'peanuts', u'argentina', u'soccer', u'might', u'abdul', u'penh',
                         u'julius', u'cartman', u'good', u'return', u'gibbs', u'than', u'food', u'nunez', u'clippers',
                         u'waged', u'starbucks', u'looney', u'sachar', u'lohan', u'bryan', u'document', u'paolozzi',
                         u'robbie', u'purdue', u'sundays', u'bridgit', u'drake', u'events', u'eleanor', u'objects',
                         u'man', u'eva', u'found', u'vasco', u'taft', u'england', u'mental', u'stiller', u'house',
                         u'fish', u'haley', u'lucie', u'brother', u'facebooks', u'tahiti', u'portland', u'hart',
                         u'randolph', u'insurance', u'really', u'lola', u'flower', u'funding', u'quincy', u'wieber',
                         u'bonham', u'robert', u'nepal', u'goebbels', u'douglas', u'research', u'cheated', u'acting',
                         u'trudeau', u'health', u'hill', u'hilo', u'brewers', u'cyclone', u'fled', u'benjamin',
                         u'paine', u'drink', u'wisconsin', u'dunn', u'dirt', u'1920s', u'yale', u'rickie', u'hepburn',
                         u'houses', u'lister', u'included', u'brightest', u'members', u'gardasil', u'put', u'matthews',
                         u'teach', u'beginning', u'bulls', u'fiat', u'cindy', u'your', u'prophet', u'stampede',
                         u'running', u'noted', u'frankel', u'american', u'w', u'rainforest', u'syria', u'joey',
                         u'financed', u'sikhism', u'flood', u'major', u'mr', u'superbowl', u'lucia', u'wilder',
                         u'girls', u'guam', u'number', u'valentine', u'dust', u'utilized', u'done', u'colombia',
                         u'pablo', u'kobe', u'firsts', u'miss', u'maple', u'temples', u'fire', u'koh', u'story',
                         u'grimm', u'temperature', u'benedict', u'arlington', u'sandusky', u'eminem', u'jeb', u'paint',
                         u'station', u'saint', u'tatu', u'garry', u'verdun', u'ecuador', u'kateri', u'baybrook',
                         u'relationship', u'jamie', u'park', u'everglades', u'part', u'jordan', u'ashley', u'albums',
                         u'believe', u'inaugurated', u'grace', u'1917', u'obama', u'king', u'umaga', u'grew', u'shrek',
                         u'fold', u'mcfly', u'zachary', u'colin', u'freud', u'jurisdiction', u'bride', u'lanzarote',
                         u'tunis', u'brahe', u'skellington', u'accomplishments', u'kindle', u'dana', u'mickey',
                         u'charlotte', u'nikolai', u'uniforms', u'imports', u'official', u'ages', u'pacquiao',
                         u'ponyboy', u'juice', u'garfield', u'fighting', u'concentration', u'bohr', u'karl', u'sell',
                         u'mountain', u'wilson', u'speaking', u'built', u'judah', u'lil', u'rukia', u'lin', u'scotland',
                         u'liv', u'caesar', u'finding', u'banjo', u'liz', u'province', u'fellowes', u'play', u'hotel',
                         u'dalmatians', u'salinger', u'serve', u'darth', u'martha', u'breaking', u'freddie', u'most',
                         u'pamela', u'sponsored', u'lawton', u'drogba', u'watt', u'kay', u'had', u'lavigne', u'galway',
                         u'seton', u'covey', u'windows', u'chicago', u'rockefeller', u'traditional', u'paulsen',
                         u'electrons', u'chester', u'pennant', u'midlothian', u'bower', u'organism', u'microsoft',
                         u'conaway', u'stones', u'stoner', u'thomas', u'rileys', u'gold', u'cheltenham', u'uga',
                         u'publisher', u'aikman', u'vader', u'nasdaq', u'finn', u'carrie', u'hornets', u'find',
                         u'occupation', u'tina', u'1912', u'northern', u'duncan', u'justice', u'writer', u'distributed',
                         u'wayne', u'pretty', u'factor', u'focker', u'cuba', u'bernstein', u'cuomo', u'kaley',
                         u'giants', u'boarding', u'harbaugh', u'his', u'hit', u'reveres', u'luke', u'express', u'kind',
                         u'trees', u'ingalls', u'famous', u'wonka', u'casino', u'during', u'him', u'dustin', u'cordova',
                         u'suarez', u'dante', u'shakiras', u'garcia', u'croatia', u'common', u'mcflys', u'x',
                         u'vincent', u'river', u'lachey', u'wrote', u'fishing', u'bars', u'miles', u'art', u'bart',
                         u'devils', u'appalachian', u'outboard', u'byron', u'bungie', u'sex', u'manning', u'see',
                         u'professional', u'reba', u'swayze', u'sea', u'riddell', u'close', u'ark', u'slam',
                         u'internationalist', u'trey', u'nemos', u'degree', u'movie', u'pavlova', u'currently',
                         u'solomon', u'lineup', u'fans', u'won', u'seychelles', u'durst', u'sixth', u'goggins',
                         u'europe', u'paisley', u'korea', u'chancellorsville', u'aguero', u'alhambra', u'nashville',
                         u'wyatt', u'aircraft', u'prieta', u'pepsi', u'genre', u'printing', u'understanding',
                         u'marilyn', u'legislature', u'league', u'last', u'serbs', u'license', u'sultan', u'anders',
                         u'crime', u'keaton', u'euros', u'cruella', u'roman', u'became', u'8am', u'annie', u'canadians',
                         u'marta', u'approve', u'rodgers', u'baltimore', u'capello', u'clone', u'childhood', u'elliot',
                         u'canadas', u'jeff', u'greensburg', u'bela', u'steele', u'leon', u'cornyn', u'tennessee',
                         u'scottish', u'faraday', u'sammy', u'mission', u'sherwin', u'devil', u'arsenal', u'instrument',
                         u'apostle', u'create', u'political', u'whos', u'johannes', u'runner', u'nicki', u'morgantown',
                         u'ireland', u'engelbart', u'nato', u'faulkner', u'assassinated', u'kurds', u'chandler',
                         u'tamera', u'walter', u'sanders', u'lived', u'squirrel', u'nrl', u'niles', u'philippine',
                         u'schuller', u'gas', u'else', u'anthony', u'1860', u'lives', u'whitney', u'demand',
                         u'diamondbacks', u'1868', u'packers', u'sami', u'mlb', u'pierce', u'georgia', u'look',
                         u'romneys', u'bill', u'elections', u'governor', u'favre', u'bronte', u'technical', u'while',
                         u'bachelors', u'smart', u'charmed', u'fun', u'luis', u'dominic', u'kareem', u'leland',
                         u'robin', u'radio', u'kingdom', u'madoff', u'sabha', u'century', u'lynette', u'bluegrass',
                         u'danes', u'ducks', u'leann', u'terminator', u'malloy', u'busch', u'monroe', u'audi',
                         u'snipes', u'barney', u'italy', u'earn', u'grant', u'barnes', u'belong', u'galapagos',
                         u'nowitzki', u'rules', u'mts', u'wall', u'grand', u'9', u'federer', u'ruth', u'spears',
                         u'shao', u'daughters', u'chagall', u'used', u'goodwin', u'keys', u'overweight', u'reds',
                         u'holidays', u'husbands', u'paxton', u'moment', u'walmart', u'uses', u'purpose', u'koch',
                         u'brussels', u'nickname', u'wheres', u'euro', u'kurdish', u'stephanie', u'poland', u'person',
                         u'cleary', u'ariels', u'nordic', u'juventus', u'sherri', u'swiss', u'horry', u'yankees',
                         u'algerian', u'composed', u'alvin', u'karnak', u'ruler', u'winkler', u'boer', u'salvation',
                         u'beth', u'press', u'roethlisberger', u'dyson', u'hobbes', u'iqbal', u'unesco', u'love',
                         u'taiwan', u'moorpark', u'forrest', u'continent', u'1800s', u'heisman', u'icelandic',
                         u'antietam', u'cup', u'marrying', u'nikki', u'appomattox', u'andorra', u'rangers',
                         u'plainfield', u'parents', u'location', u'sydney', u'baskett', u'circumcision', u'armie',
                         u'huey', u'pompeii', u'bin', u'bio', u'customers', u'marco', u'inaugural', u'monica', u'big',
                         u'beals', u'sneeze', u'dubai', u'wilkins', u'wives', u'game', u'earharts', u'gama', u'waynes',
                         u'lassen', u'bullock', u'waukesha', u'sandals', u'intel', u'mariah', u'd', u'moira',
                         u'according', u'capitals', u'gaiman', u'donne', u'duluth', u'donna', u'ivan', u'mcgraw',
                         u'pippen', u'fault', u'brett', u'harlem', u'1958', u'doherty', u'google', u'brakes', u'senate',
                         u'spring', u'fathers', u'some', u'back', u'bach', u'economic', u'warhols', u'palo',
                         u'wonderland', u'gyllenhaal', u'berger', u'riel', u'savage', u'qatar', u'sheen', u'serena',
                         u'stabler', u'thanksgiving', u'supreme', u'newark', u'religion', u'prom', u'civilization',
                         u'bradman', u'anne', u'dating', u'monroes', u'invade', u'anna', u'be', u'hammond', u'run',
                         u'ba', u'bc', u'cutler', u'pieces', u'gosselin', u'streetcar', u'leibovitz', u'odom', u'santa',
                         u'from', u'lyrics', u'maccabees', u'by', u'santi', u'russell', u'1979', u'beane', u'works',
                         u'jamarcus', u'usa', u'corpse', u'manny', u'lindsey', u'stonewall', u'melbourne', u'range',
                         u'illegal', u'griffins', u'arcangel', u'dwight', u'muslims', u'gospel', u'jimmy', u'clinton',
                         u'colorado', u'hometown', u'diwali', u'kat', u'montpelier', u'celebrities', u'osama',
                         u'wassily', u'carlton', u'middleton', u'parton', u'steven', u'motors', u'france', u'lebron',
                         u'nsw', u'canal', u'sonny', u'ontario', u'ptolemy', u'swedens', u'kroenke', u'long',
                         u'taliban', u'elizabethtown', u'mccartney', u'grave', u'heritage', u'beyonces', u'segel',
                         u'vienna', u'files', u'zealand', u'fabio', u'himself', u'bethenny', u'jewish', u'wheldon',
                         u'murphy', u'youth', u'hammett', u'films', u'mcclure', u'larry', u'reed', u'authority',
                         u'frida', u'russian', u'episode', u'crane', u'junior', u'heinrich', u'fda', u'utc',
                         u'degenerous', u'kellie', u'biggie', u'consist', u'langhorne', u'bligh', u'gottfried', u'us',
                         u'malis', u'lords', u'nestle', u'un', u'pres', u'uk', u'guyana', u'mozambique', u'z',
                         u'chelsea', u'called', u'bell', u'sort', u'v', u'associated', u'roshon', u'armstrong',
                         u'expedition', u'tyrese', u'malthus', u'scarlet', u'brazilians', u'suffragettes', u'abrams',
                         u'rupert', u'work', u'graham', u'empire', u'phantom', u'rainy', u'lemon', u'berkshire',
                         u'sanzio', u'edwards', u'zhao', u'globetrotters', u'kirk', u'ellen', u'abarth', u'department',
                         u'artistic', u'dale', u'gimlis', u'lena', u'claus', u'ryans', u'kansas', u'papa', u'janelle',
                         u'frances', u'william', u'meaning', u'yangs', u'fisher', u'song', u'chocolate', u'developed',
                         u'desert', u'hackney', u'kors', u'lang', u'casey', u'lane', u'land', u'e', u'lana', u'vice',
                         u'dvd', u'age', u'barkley', u'youtube', u'heath', u'2002', u'2003', u'2000', u'2001',
                         u'thames', u'2007', u'2005', u'walker', u'nash', u'2009', u'having', u'buonarroti',
                         u'aguilera', u'katy', u'hampton', u'code', u'jason', u'iraqi', u'abramovich', u'zoey',
                         u'steve', u'bacardi', u'ypres', u'gana', u'jimi', u'ga', u'go', u'golf', u'gm', u'golfer',
                         u'contributions', u'kate', u'toni', u'cody', u'copernicus', u'1908', u'compose', u'vinci',
                         u'baron', u'turkish', u'cruises', u'mcclarnon', u'young', u'tomtom', u'appointed',
                         u'languages', u'cartier', u'dickinson', u'suite', u'maryland', u'include', u'hedberg',
                         u'scarlett', u'queen', u'seized', u'sage', u'larusso', u'landforms', u'sabin', u'cashs',
                         u'barbara', u'facebook', u'assad', u'tuts', u'darry', u'tutu', u'clement', u'bryant', u'duffy',
                         u'balboa', u'magic', u'airtran', u'prix', u'knight', u'marry', u'grammar', u'michael', u'ryan',
                         u'murdoch', u'winter', u'this', u'race', u'gupta', u'islamabad', u'gauge', u'1665',
                         u'leonardo', u'gallipoli', u'harper', u'bernie', u'claudia', u'rutherford', u'carter', u'crow',
                         u'participate', u'mediterranean', u'euphrates', u'rivers', u'daoism', u'odi', u'video',
                         u'traveling', u'jared', u'anton', u'demeters', u'mussolini', u'vesalius', u'edison', u'plays',
                         u'compaq', u'paintings', u'morse', u'falcons', u'leno', u'vampire', u'indian', u'twins',
                         u'capital', u'collins', u'nicholas', u'bird', u'nazis', u'phoebe', u'body', u'lea', u'nearest',
                         u'led', u'lee', u'chinas', u'exchange', u'yoruba', u'underwood', u'judges', u'leo', u'luiz',
                         u'following', u'explore', u'ramsey', u'them', u'making', u'spratly', u'sing', u'invented',
                         u'terrys', u'ukraine', u'morocco', u'great', u'kissinger', u'receive', u'involved',
                         u'cleopatra', u'30', u'alaska', u'products', u'volga', u'lochte', u'behead', u'makes',
                         u'honor', u'holmes', u'control', u'named', u'firefox', u'clark', u'reserve', u'egypt', u'win',
                         u'clara', u'private', u'hardy', u'austria', u'radcliffe', u'clary', u'names', u'motor',
                         u'lima', u'wiz', u'gibbys', u'standing', u'use', u'andreas', u'usc', u'zip', u'connery',
                         u'coached', u'archbishop', u'gregor', u'hudson', u'theme', u'next', u'circumstances', u'randy',
                         u'debbie', u'butler', u'eagles', u'bonds', u'jonathan', u'clemenceau', u'lutz', u'iselin',
                         u'parliament', u'babe', u'rich', u'started', u'zimmer', u'about', u'missile', u'stephenie',
                         u'trail', u'train', u'clemens', u'debussy', u'escape', u'8', u'baby', u'ok', u'santana',
                         u'mitsubishi', u'iii', u'velazquez', u'women', u'darwin', u'animals', u'britney', u'f',
                         u'ricans', u'gabriel', u'athlete', u'oh', u'puntland', u'archer', u'of', u'mesopotamia',
                         u'isabellas', u'tour', u'galera', u'tarantino', u'fringe', u'kenny', u'thermopylae', u'patron',
                         u'jermaine', u'katherine', u'etta', u'benz', u'halloween', u'trap', u'high', u'peoria',
                         u'blaine', u'bessie', u'bones', u'dominant', u'tcp', u'reynolds', u'native', u'afl',
                         u'summers', u'united', u'kossuth', u'sit', u'six', u'poetry', u'afb', u'camille', u'located',
                         u'winners', u'labor', u'animal', u'abzug', u'visas', u'kravitz', u'rousseau', u'schaub',
                         u'honda', u'attend', u'sir', u'farm', u'watch', u'act', u'leukemia', u'gardner', u'franklins',
                         u'ronald', u'monaghan', u'structure', u'ethnic', u'reggie', u'stephens', u'aeros', u'clooney',
                         u'npr', u'muppets', u'boeing', u'democracy', u'guatemala', u'matisse', u'wwii', u'starr',
                         u'claire', u'scrubs', u'pyramids', u'napoleons', u'spaniels', u'jolie', u'divided', u'breast',
                         u'houston', u'fearless', u'fresno', u'bilbo', u'manufactured', u'asiana', u'desmond', u'vma',
                         u'produced', u'lands', u'biermann', u'motorcycle', u'quake', u'cruise', u'mraz', u'galaxy',
                         u'warren', u'perfect', u'1', u'blake', u'hepburns', u'brian', u'terriers', u'landed',
                         u'woodson', u'shelleys', u'lt', u'tyler', u'degrees', u'outen', u'puerto', u'alexander',
                         u'2011', u'2010', u'2013', u'2012', u'dad', u'freeman', u'nadi', u'vonnegut', u'zagreb',
                         u'surrounds', u'wolfgang', u'dan', u'practice', u'mcenroe', u'runs', u'skywalkers', u'essex',
                         u'newman', u'monifah', u'snoopy', u'maslow', u'augustus', u'cage', u'mccoy', u'presidential',
                         u'worlds', u'masters', u'airports', u'davidson', u'university', u'nfl', u'vanderbilts',
                         u'lifetime', u'chickasaw', u'morris', u'rockets', u'betty', u'feldman', u'chesapeake',
                         u'warner', u'marlee', u'mets', u'studios', u'hathaway', u'chung', u'doing', u'poppins',
                         u'gary', u'programmed', u'1976', u'elementary', u'books', u'linnaeus', u'emmitt', u'wade',
                         u'edisons', u'our', u'adlington', u'marley', u'bigfoot', u'shannon', u'out', u'havasu',
                         u'kevorkian', u'matt', u'nick', u'braxton', u'mcmahon', u'northman', u'rev', u'day', u'ricky',
                         u'unitarian', u'potomac', u'arkansas', u'mcelderry', u'cromwell', u'cause', u'krakowski',
                         u'red', u'achievements', u'harold', u'jessica', u'eco', u'frank', u'molly', u'switzerland',
                         u'jill', u'york', u'celtics', u'philip', u'princess', u'cristina', u'chiefs', u'waterloo',
                         u'g', u'earp', u'hollywood', u'florida', u'mac', u'times', u'explored', u'adrian', u'davis',
                         u'cain', u'hussein', u'austin', u'south', u'lovato', u'genetics', u'matthias', u'flyers',
                         u'owned', u'jesus', u'muhammad', u'congo', u'hugo', u'1886', u'owner', u'priestley', u'pryor',
                         u'ancient', u'reference', u'ferris', u'festival', u'maurice', u'system', u'elric', u'avengers',
                         u'their', u'attack', u'cats', u'rocha', u'voldemort', u'palestine', u'downey', u'pakistani',
                         u'final', u'benghazi', u'georgetown', u'bledsoe', u'stars', u'academy', u'allied', u'exactly',
                         u'contribute', u'megan', u'environmental', u'regards', u'bieber', u'spiegel', u'mannings',
                         u'mendlers', u'july', u'moriarty', u'clarkson', u'zones', u'babys', u'valley', u'ben',
                         u'grandson', u'culture', u'split', u'coast', u'inventor', u'tommy', u'roberts', u'anaheim',
                         u'hispanic', u'ferry', u'sr', u'dynamo', u'doctorate', u'sumpter', u'coronation', u'gretzkys',
                         u'jonesboro', u'are', u'wittle', u'palmer', u'violets', u'journey', u'julian', u'cohen',
                         u'muir', u'roosevelts', u'cricket', u'bentley', u'chapman', u'tonight', u'pemberton',
                         u'dingle', u'goldberg', u'ethnically', u'have', u'keller', u'need', u'purgatory', u'border',
                         u'catholic', u'bomer', u'russians', u'dallas', u'needle', u'chief', u'battles', u'ishmaels',
                         u'belief', u'which', u'kaplan', u'so', u'techniques', u'sirius', u'medals', u'heisenberg',
                         u'brazil', u'grenville', u'kelly', u'gerard', u'doug', u'furious', u'montana', u'iberian',
                         u'highschool', u'sally', u'herman', u'laurent', u'mitch', u'frederick', u'disease', u'ramirez',
                         u'soprano', u'se', u'fowler', u'five', u'mick', u'maasai', u'batgirl', u'gain', u'son',
                         u'affair', u'parker', u'chadwick', u'lorne', u'tolkien', u'rings', u'charles', u'bring',
                         u'senegal', u'kitt', u'postcode', u'sahel', u'dorothy', u'ottoman', u'chicken', u'partners',
                         u'durant', u'filmed', u'based', u'knowledge', u'jay', u'sparks', u'housewives', u'winner',
                         u'frenchs', u'controls', u'should', u'terminal', u'hector', u'hopi', u'bombings', u'lassiter',
                         u'milian', u'marriage', u'communist', u'gillard', u'move', u'statham', u'beat', u'succeeded',
                         u'michigan', u'massacre', u'littleton', u'cubs', u'words', u'presley', u'richards', u'score',
                         u'years', u'jeannie', u'kardashians', u'areas', u'mcnair', u'symbols', u'evolution',
                         u'bradenton', u'places', u'twice', u'bisect', u'denmark', u'married', u'lala', u'taxes',
                         u'teams', u'kailua', u'qb', u'she', u'painter', u'tunes', u'ohio', u'angeles', u'steelers',
                         u'gibson', u'eowyn', u'albertini', u'albania', u'skywest', u'exists', u'timezones',
                         u'national', u'lamar', u'canucks', u'computer', u'chuck', u'desperate', u'greece', u'racket',
                         u'volvo', u'gonzalez', u'creating', u'closer', u'wire', u'wealth', u'turks', u'guyanese',
                         u'landry', u'utahs', u'state', u'supernatural', u'bruno', u'nuclear', u'colombian', u'ken',
                         u'hefner', u'cristiano', u'tripadvisor', u'brentwood', u'opening', u'trinians', u'joy',
                         u'zambezi', u'khartoum', u'duane', u'job', u'queensland', u'joe', u'armenia', u'nicolaus',
                         u'kevjumba', u'wh', u'2pm', u'jon', u'marty', u'miwok', u'career', u'rizzo', u'wnba', u'drug',
                         u'rams', u'admit', u'harvard', u'constantine', u'tutsi', u'bronx', u'hammurabi', u'jersey',
                         u'wale', u'co', u'huang', u'universalist', u'cc', u'ca', u'speaker', u'zellweger', u'mengele',
                         u'walk', u'walt', u'ljungberg', u'cy', u'carver', u'cs', u'kings', u'furcal', u'oakland',
                         u'undergraduate', u'appeared', u'ct', u'willy', u'provinces', u'kenobi', u'midland',
                         u'heyerdahl', u'prince', u'sara', u'bbc', u'quiz', u'restless', u'rhode', u'kahn', u'winnipeg',
                         u'fawcett', u'agreements', u'hawking', u'gaza', u'cena', u'louisiana', u'naples', u'killed',
                         u'mike', u'liverpool', u'general', u'earnhardt', u'aubrey', u'zoroastrian', u'eduardo', u'hmv',
                         u'pelosi', u'goddess', u'tycho', u'buffy', u'player', u'deep', u'stoppables', u'atlanta',
                         u'ravens', u'spain', u'weston', u'novel', u'blackstreet', u'taped', u'bahama', u'fitzgerald',
                         u'as', u'salman', u'augusta', u'will', u'stalin', u'ithaca', u'ar', u'jumanji', u'owns',
                         u'maui', u'discoveries', u'resigns', u'chernobyl', u'sith', u'va', u'bengals', u'vi', u'demi',
                         u'helped', u'simone', u'vt', u'sherlock', u'dual', u'vw', u'arabia', u'arabic', u'thor',
                         u'jenner', u'shooting', u'brockovich', u'tupac', u'floyds', u'juan', u'buddhist', u'pauls',
                         u'cross', u'jenna', u'member', u'matthew', u'parts', u'swift', u'utica', u'dickens',
                         u'largest', u'party', u'foxs', u'gets', u'paula', u'ziva', u'ball', u'columbia', u'bali',
                         u'boozer', u'samantha', u'buzz', u'romeo', u'coaches', u'giuliana', u'phx', u'wiesel',
                         u'sisters', u'campus', u'colts', u'whitmans', u'cazorla', u'off', u'center', u'i',
                         u'indonesia', u'seth', u'flanagan', u'antonio', u'theodor', u'audie', u'english', u'position',
                         u'soviet', u'faramir', u'deion', u'reside', u'nadal', u'stores', u'kkk', u'percent', u'wagner',
                         u'dennings', u'himmler', u'cabo', u'2008', u'clocks', u'lincolns', u'shiloh', u'dakota',
                         u'paul', u'lauren', u'tulane', u'griffith', u'jean', u'buellers', u'web', u'perpignan',
                         u'winchester', u'lichtenstein', u'drunk', u'smith', u'lake', u'bench', u'sullivan', u'other',
                         u'aruba', u'palestrina', u'ski', u'earthquakes', u'nate', u'gmt', u'assyrian', u'sonia',
                         u'government', u'utah', u'february', u'republics', u'fuji', u'doyle', u'belgium', u'knox',
                         u'crusher', u'revelstoke', u'jolies', u'pollocks', u'lincoln', u'emma', u'like', u'lost',
                         u'miami', u'pepys', u'schmitt', u'dodgeball', u'canyon', u'despicable', u'roth', u'peron',
                         u'cletus', u'sarajevo', u'martin', u'become', u'starred', u'conrad', u'refugees', u'vasquez',
                         u'amd', u'italian', u'lance', u'church', u'searching', u'birmingham', u'haim', u'hair',
                         u'pregnancy', u'daylight', u'babbage', u'export', u'abolitionist', u'cleveland', u'home',
                         u'halifax', u'peter', u'shakira', u'jojo', u'maxie', u'est', u'jeremy', u'diaries', u'lead',
                         u'billy', u'garrett', u'momsen', u'hurricane', u'mines', u'fedex', u'does', u'jfks',
                         u'constitute', u'wendt', u'leader', u'swifts', u'muharram', u'birthday', u'schedule', u'mitt',
                         u'stowe', u'wesley', u'pizarro', u'carnegie', u'r', u'counties', u'sister', u'actual',
                         u'justin', u'kevin', u'getting', u'gutenberg', u'recognized', u'kourtney', u'slayer',
                         u'teotihuacan', u'empty', u'whistler', u'segovia', u'tomb', u'emperor', u'balkan', u'burma',
                         u'channing', u'own', u'letters', u'childrens', u'glenn', u'dubois', u'washington', u'raquel',
                         u'stan', u'playoff', u'weather', u'promise', u'registration', u'austen', u'yankee', u'ruffin',
                         u'mississippi', u'vai', u'van', u'vespucci', u'1980', u'texaco', u'hatshepsut', u'vegetables',
                         u'daniels', u'1988', u'continental', u'beneke', u'kelso', u'slovakia', u'biggest', u'parkers',
                         u'laredo', u'michelangelo', u'buy', u'north', u'tomlinson', u'neighbors', u'charlemagnes',
                         u'bosnian', u'brand', u'haberkorn', u'pharaoh', u'hw', u'pixie', u'natalie', u'goals',
                         u'apollo', u'eat', u'he', u'embargo', u'challenges', u'made', u'farrah', u'hooke', u'tallest',
                         u'cells', u'mozart', u'signed', u'greyton', u'record', u'ruling', u'sacha', u'sponsor',
                         u'burress', u'irish', u'andean', u'universal', u'penny', u'romney', u'pie', u'iverson',
                         u'erin', u'wollstonecraft', u'conan', u'erik', u'aristotle', u'radke', u'brembo', u'education',
                         u'draco', u'eric', u'visa', u'jesse', u'diego', u'pierluigi', u'contest', u'corporation',
                         u'boot', u'illinois', u'dogtown', u'old', u'book', u'gossip', u'vacation', u'branch', u'finch',
                         u'machiavelli', u'predominant', u'nra', u'nelson', u'juni', u'irons', u'francisco', u'star',
                         u'shakespeares', u'missouri', u'june', u'stay', u'margaret', u'ferland', u'thoreau', u'kinda',
                         u'nintendo', u'sandler', u'friends', u'howie', u'christians', u'dolphins', u'ghost',
                         u'mcqueen', u'using', u'samsung', u'kardashian', u'resolution', u'accomplice', u'factors',
                         u'jewel', u'rule', u'original', u'elaine', u'courson', u'heidi', u'padme', u'richardson',
                         u'simpson', u'representative'}


def _read_clueweb_data():
    global _clueweb_entitypairs_langmodel
    global _clueweb_entitypairs_embeddings

    entitypairs_totalcount = dict()
    clueweb_data_cache_filename = globals.config.get("WebSearchFeatures", "clueweb-entitypair-counts-cache-file")
    if os.path.exists(clueweb_data_cache_filename):
        logger.info("Reading ClueWeb entity pair cache data...")
        with open(clueweb_data_cache_filename, 'r') as cache_file:
            _clueweb_entitypairs_langmodel, _clueweb_entitypairs_embeddings = pickle.load(cache_file)
        logger.info("Done reading ClueWeb entity pair cache data!")
    else:
        clueweb_data_filename = globals.config.get("WebSearchFeatures", "clueweb-entitypair-counts-file")
        with gzip.open(clueweb_data_filename, 'r') as clueweb_data_file:
            logger.info("Reading ClueWeb entity pair data...")
            embeddings = get_embeddings()
            _clueweb_entitypairs_langmodel = dict()
            _clueweb_entitypairs_embeddings = dict()
            for index, line in enumerate(clueweb_data_file):
                fields = line.strip().split("\t")
                mid1 = fields[0].replace("/", ".")[1:]
                mid2 = fields[2].replace("/", ".")[1:]
                entity_pair = (mid1, mid2)
                if (mid2, mid1) in _clueweb_entitypairs_langmodel:
                    entity_pair = (mid2, mid1)
                if entity_pair not in _clueweb_entitypairs_langmodel:
                    _clueweb_entitypairs_langmodel[entity_pair] = dict()
                    _clueweb_entitypairs_embeddings[entity_pair] = np.zeros(embeddings.embeddings.vector_size)
                    entitypairs_totalcount[entity_pair] = 0

                for word in fields[4:]:
                    word_count = word.split(":")
                    count = int(word_count[-1])
                    entitypairs_totalcount[entity_pair] += count
                    word = ":".join(word_count[:-1])
                    if word in embeddings.embeddings:
                        _clueweb_entitypairs_embeddings[entity_pair] += embeddings[word] * count

                    if word in webquestions_term_set:
                        old_count = _clueweb_entitypairs_langmodel[entity_pair].get(word, 0)
                        _clueweb_entitypairs_langmodel[entity_pair][word] = old_count + count

                if index % 1000 == 0:
                    print "%d lines processed" % index
        logger.info("Normalizing ClueWeb count scores...")
        for entity_pair, word_counts in _clueweb_entitypairs_langmodel.iteritems():
            _clueweb_entitypairs_langmodel[entity_pair] = dict((word, 1.0 * count / entitypairs_totalcount[entity_pair])
                                                               for word, count in word_counts.iteritems())
            _clueweb_entitypairs_embeddings[entity_pair] /= entitypairs_totalcount[entity_pair]
        logger.info("Caching ClueWeb data...")
        with open(clueweb_data_cache_filename, 'w') as out:
            pickle.dump((_clueweb_entitypairs_langmodel, _clueweb_entitypairs_embeddings), out)
        logger.info("Done reading ClueWeb data!")


def get_entitypair_langmodel(entity_pair):
    if _clueweb_entitypairs_langmodel is None:
        _read_clueweb_data()
    if entity_pair in _clueweb_entitypairs_langmodel:
        return _clueweb_entitypairs_langmodel[entity_pair]
    elif (entity_pair[1], entity_pair[0]) in _clueweb_entitypairs_langmodel:
        return _clueweb_entitypairs_langmodel[(entity_pair[1], entity_pair[0])]
    return dict()


def get_entitypair_embeddings(entity_pair):
    if _clueweb_entitypairs_embeddings is None:
        _read_clueweb_data()
    if entity_pair in _clueweb_entitypairs_embeddings:
        return _clueweb_entitypairs_embeddings[entity_pair]
    elif (entity_pair[1], entity_pair[0]) in _clueweb_entitypairs_embeddings:
        return _clueweb_entitypairs_embeddings[(entity_pair[1], entity_pair[0])]
    return np.zeros(get_embeddings().embeddings.vector_size)


def get_langmodel_score(entity_pair, question_tokens):
    lang_model = get_entitypair_langmodel(entity_pair)
    return -sum(log(lang_model[term]) for term in question_tokens if term in lang_model)


def get_embedding_score(entity_pair, question_tokens):
    embeddings = get_embeddings()
    return np.dot(matutils.unitvec(np.array([embeddings[term]
                                             for term in question_tokens
                                             if term in embeddings.embeddings])
                                   .mean(axis=0)),
                  matutils.unitvec(get_entitypair_embeddings(entity_pair)))


def generate_clueweb_features(candidate):
    question_entities = [entity.entity.entity.id for entity in candidate.matched_entities
                         if isinstance(entity.entity.entity, KBEntity)]
    answer_entities = [mid for answer_entity_name in candidate.get_results_text()
                       for mid in KBEntity.get_entityid_by_name(answer_entity_name, keep_most_triples=True)]
    question_tokens = [token for token in tokenize(candidate.query.original_query)]

    scores = []
    emb_scores = []

    # Get their language models and score against the question terms...
    for question_entity in question_entities:
        for answer_entity in answer_entities:
            scores.append(get_langmodel_score((question_entity, answer_entity), question_tokens))
            emb_scores.append(get_embedding_score((question_entity, answer_entity), question_tokens))

    if not scores:
        return dict()

    return {
        "clueweb_feature:max_score": max(scores),
        "clueweb_feature:min_score": min(scores),
        "clueweb_feature:avg_score": avg(scores),
        "clueweb_feature:max_emb_score": max(emb_scores),
        "clueweb_feature:min_emb_score": min(emb_scores),
        "clueweb_feature:avg_emb_score": avg(emb_scores),
    }


if __name__ == "__main__":
    pass
